export const USERS = {
    ACTIONS: {
        USERS_SET: "USERS_ACTIONS_USERS_SET",
        CURRENT_SET: "USERS_ACTIONS_USER_CURRENT_SET",
        MODAL_TOGGLE: "USERS_ACTIONS_MODAL_TOGGLE"
    },
    MODALS: {
        USER_NEW: "USER_NEW"
    }
};